# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_title', models.CharField(max_length=100)),
                ('outline', models.CharField(max_length=200)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('view_num', models.IntegerField(default=0)),
                ('collect_num', models.IntegerField(default=0)),
                ('contenttypeid', models.IntegerField()),
                ('contentid', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('recimfor', models.CharField(choices=[('REC', 'REC'), ('NOREC', 'NOREC')], default='NOREC', max_length=2)),
                ('content_image', models.ImageField(null=True, upload_to='contentimage/')),
            ],
        ),
        migrations.CreateModel(
            name='icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=20)),
                ('labeid', models.IntegerField()),
            ],
        ),
    ]
