# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_delete_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=20)),
                ('labeid', models.IntegerField()),
                ('icon_image', models.ImageField(null=True, upload_to='iconimage/')),
            ],
        ),
    ]
