# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20170506_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=30)),
                ('wechat_openid', models.CharField(max_length=50)),
                ('true_name', models.CharField(max_length=20)),
                ('collect', models.TextField(null=True)),
            ],
        ),
    ]
